# Generated by Django 3.2.6 on 2021-11-17 12:57

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('color', models.CharField(default='#a0a0a0', help_text='Use hexadecimal format like #a0a0a0', max_length=7, validators=[django.core.validators.RegexValidator('#[a-fA-F0-9]{6}')])),
            ],
        ),
        migrations.CreateModel(
            name='TrackedPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('altitude_accuracy', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
